# Generated by Django 2.2.11 on 2020-04-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='house_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='id_num',
            field=models.IntegerField(default=99101015030080),
        ),
    ]
